### ISSUE TITLE
This is a Question, no ISSUE

### ISSUE THREAD

**Issue by the-hotmann** [DMKEBUSINESSGMBH/mkvarnish#2]
1.) Does this Extension support Varnish 6.1?
2.) Does this Extension wipe the cache of pages which got updated ion the Typo3 Backend automaticaly?
3.) Does this Extension support forcing caching?
3.1) Example: I have a page which Typo3 says its not cachable but it indeed is, can I somewhere force it to be cached?

Thanks for answering, would love to implement a good Varnish Cache!

**Comment by hannesbochmann** [comment]
1) I haven't tested this but I see no reason why not. The extension communicates with varnish only by sending PURGE requests and setting Headerdata.
2) yes.
3) No, the extension completely relies on TYPO3 what should be cached and what not. But why would TYPO3 say a page is not cachable if it is anyway?

**Comment by rengaw83** [comment]
Hi @M4rt1n17 

1. To clear cache entries mkvarnish sends a PURGE request to the Varnish-Proxy. The flush/flush depends on your Varnish configuration and should work with every version of varnis.

2. mkvarnish  automatically clears the page cache, even the cache of detail plugins like news, if a news has been changed.

3. mkvarnish does not modify the cache headers set by typo3. 
So no, you can not force the caching of a noncachable site with this extension.
If typo3 says this site is not cacheable, then this has a reason.

**Comment by the-hotmann** [comment]
> Hi @M4rt1n17
> 
> 1. To clear cache entries mkvarnish sends a PURGE request to the Varnish-Proxy. The flush/flush depends on your Varnish configuration and should work with every version of varnis.
> 2. mkvarnish  automatically clears the page cache, even the cache of detail plugins like news, if a news has been changed.
> 3. mkvarnish does not modify the cache headers set by typo3.
>    So no, you can not force the caching of a noncachable site with this extension.
>    If typo3 says this site is not cacheable, then this has a reason.

Thanks for your reply guys.

1. thanks so I will try it with Varnish 6.1.1
2. thats good.
3. well actually some forms are not cachable by TYPO3 also pages which are "under" a invisible Page are not cachable by TYPO3.
4. staticfilecache got some "force Caching" which is overwriting TYPO3 "is cachable" would love to see that here aswell because also G-Maps seems not to be cachable by TYPO3 and a force to cache would solve all this issues. But I will report back after implementing it.
